spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: techtask
    password: techtask
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect